<template>
  <div class="carList" v-loading="loading">
       <template>
            <el-table
            :data="tableData"
            height="80vh"
            border
            size="small"
            style="width: 100%">
            <el-table-column
                prop="licenseno"
                align="center"
                fixed
                width="120px"
                label="车牌号">
            </el-table-column>
            <el-table-column
                prop="carvin"
                align="center"
                width="185px"
                label="车架号">
            </el-table-column>
            <el-table-column
                prop="engineNo"
                align="center"
                width="155px"
                label="发动机号">
            </el-table-column>
            <el-table-column
                prop="registerDate"
                align="center"
                width="120px"
                label="车辆注册日期">
            </el-table-column>
            <el-table-column
                prop="guaranteeDate"
                align="center"
                width="120px"
                label="商业险到期日期">
            </el-table-column>
            <el-table-column
                prop="sex"
                align="center"
                label="性别">
            </el-table-column>
            <el-table-column
                prop="mobile"
                align="center"
                width="120px"
                label="联系电话">
            </el-table-column>
            <el-table-column
                prop="carModel"
                align="center"
                width="80px"
                label="品牌">
            </el-table-column>
            <el-table-column
                prop="modelName"
                width="100px"
                show-overflow-tooltip
                align="center"
                label="品牌型号">
            </el-table-column>
            <el-table-column
                prop="styleYear"
                align="center"
                label="年款">
            </el-table-column>
            <el-table-column
                prop="displacement"
                align="center"
                label="排量">
            </el-table-column>
            <el-table-column
                prop="driveType"
                align="center"
                label="驱动类型">
            </el-table-column>
            <el-table-column
                prop="engineNum"
                align="center"
                label="引擎号">
            </el-table-column>
            <el-table-column
                prop="derailleur"
                align="center"
                show-overflow-tooltip
                label="变速器">
            </el-table-column>
            <el-table-column
                prop="refPrice"
                align="center"
                label="参考价（万）">
            </el-table-column>
            <el-table-column
                prop="userName"
                align="center"
                show-overflow-tooltip
                width="100px"
                label="车主姓名">
            </el-table-column>
            
            <el-table-column
                prop="age"
                align="center"
                label="年龄">
            </el-table-column>
            <el-table-column
                prop="falseAreaCode"
                align="center"
                label="区域">
            </el-table-column>
            <el-table-column
                prop="fuelType"
                align="center"
                label="燃油类型">
            </el-table-column>
            <el-table-column
                prop="gearNum"
                align="center"
                label="档位数">
            </el-table-column>
            <el-table-column
                prop="carbody"
                align="center"
                label="车身">
            </el-table-column>
            <el-table-column
                prop="carbodyStr"
                align="center"
                label="车身结构">
            </el-table-column>
            <el-table-column
                prop="listYear"
                align="center"
                width="120px"
                label="上市年份">
            </el-table-column>
            <el-table-column
                prop="stopProDate"
                align="center"
                width="120px"
                label="停产日期">
            </el-table-column>
            <el-table-column
                prop="carType"
                align="center"
                label="车型">
            </el-table-column>
            <el-table-column
                prop="licenseType"
                align="center"
                width="120px"
                label="车型代码">
            </el-table-column>
            <el-table-column
                prop="inletForm"
                align="center"
                label="进气形式">
            </el-table-column>
            
            <el-table-column
                prop="premium"
                align="center"
                label="保费">
            </el-table-column>
            <el-table-column
                prop="seatCount"
                align="center"
                label="座位数">
            </el-table-column>
            </el-table>
            <el-pagination
            style="float:right"
            @size-change="handleSizeChange"
            @current-change="handleCurrentChange"
            :current-page="page"
            :page-sizes="[20 ,100, 200, 300, 400 ,1000]"
            :page-size="pageSize"
            layout="total, sizes, prev, pager, next, jumper"
            :total="total">
            </el-pagination>
        </template>
  </div>
</template>

<script>
import { carInfos } from '@/api/api.js'
export default {
    name:'carList',
    data(){
        return{
            tableData:[],
            page:1,
            pageSize:20,
            loading:false,
            total:0
        }
    },
    methods:{
        handleSizeChange(val) {//每页
          this.pageSize=val
          this.carInfos()
        },
        handleCurrentChange(val) {//翻页
          this.page=val
          this.carInfos()
        },
        carInfos(){
            let data={
                page:this.page-1,
                pageSize:this.pageSize,
            }
            this.loading=true
            carInfos(data).then(res=>{
                this.loading=false
                if(res.data.code==1){
                    this.tableData=res.data.body.data
                    this.tableData.forEach(item=>{
                        item.mobile=item.mobile.substring(0,3)+'****'+item.mobile.substring(7,item.mobile.length)
                    })
                    this.total=res.data.body.count
                }
            })
        }
    },
    mounted(){
        this.carInfos()
    }
}
</script>

<style lang="less" scoped>

</style>